const c=document.getElementById('game'),ctx=c.getContext('2d');
const W=1280,H=720,FLOOR=645;let scale=1,ox=0,oy=0;
let px=220,py=560,vx=0,vy=0,facing=1,score=0,lives=3,parts=0,fuel=0,stage=1,gameOver=false;
let bullets=[],enemies=[],pickups=[],stars=[],fireCd=0,last=performance.now();
const keys={left:false,right:false,thrust:false,fire:false};
function resize(){const dpr=Math.min(devicePixelRatio||1,2);c.width=innerWidth*dpr;c.height=innerHeight*dpr;const sx=c.width/W,sy=c.height/H;scale=Math.min(sx,sy);ox=(c.width-W*scale)/2;oy=(c.height-H*scale)/2}
addEventListener('resize',resize);resize();
for(let i=0;i<70;i++)stars.push({x:Math.random()*W,y:Math.random()*H*.75,s:1+Math.random()*2});
function spawnEnemy(){const side=Math.random()<.5?1:-1;enemies.push({x:side===1?30:W-30,y:120+Math.random()*430,vx:(95+Math.random()*135)*side,vy:-40+Math.random()*80,p:Math.random()*6.28,t:Math.floor(Math.random()*4)})}
function resetStage(){enemies=[];bullets=[];pickups=[];for(let i=0;i<Math.min(4+stage,10);i++)spawnEnemy();pickups.push({k:'part',x:500,y:585,t:false},{k:'part',x:720,y:515,t:false},{k:'part',x:900,y:585,t:false},{k:'fuel',x:1040,y:535,t:false});px=220;py=560;vx=vy=0;parts=fuel=0}
resetStage();
function hitPlayer(){lives--;px=220;py=560;vx=vy=0;if(lives<=0)gameOver=true}
function update(dt){if(gameOver)return;if(keys.left){vx-=1150*dt;facing=-1}if(keys.right){vx+=1150*dt;facing=1}vx*=Math.pow(.001,dt);vx=Math.max(-320,Math.min(320,vx));if(keys.thrust)vy-=1250*dt;vy+=820*dt;vy=Math.max(-480,Math.min(520,vy));px+=vx*dt;py+=vy*dt;if(px<20)px=W-20;if(px>W-20)px=20;if(py>FLOOR-24){py=FLOOR-24;vy=0}if(py<70){py=70;vy=Math.max(0,vy)}fireCd-=dt;if(keys.fire&&fireCd<=0){bullets.push({x:px+28*facing,y:py-4,vx:760*facing,l:1.6});fireCd=.17}
for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.vx*dt;b.l-=dt;let dead=b.l<=0||b.x<-40||b.x>W+40;for(let j=enemies.length-1;j>=0&&!dead;j--){let e=enemies[j],dx=b.x-e.x,dy=b.y-e.y;if(dx*dx+dy*dy<900){enemies.splice(j,1);score+=100;dead=true}}if(dead)bullets.splice(i,1)}
for(const e of enemies){e.p+=dt*(1.5+e.t*.3);e.x+=e.vx*dt;e.y+=e.vy*dt+Math.sin(e.p)*(28+e.t*10)*dt;if(e.x<-60)e.x=W+60;if(e.x>W+60)e.x=-60;if(e.y<95){e.y=95;e.vy=Math.abs(e.vy)}if(e.y>FLOOR-35){e.y=FLOOR-35;e.vy=-Math.abs(e.vy)}const dx=e.x-px,dy=e.y-py;if(dx*dx+dy*dy<1156){hitPlayer();break}}
if(enemies.length<Math.min(4+stage,10)&&Math.random()<dt*.35)spawnEnemy();for(const p of pickups){if(p.t)continue;const dx=p.x-px,dy=p.y-py;if(dx*dx+dy*dy<1936){p.t=true;if(p.k==='part'){parts++;score+=250}else{fuel++;score+=150}}}if(parts>=3&&fuel>=1){score+=1000;stage++;resetStage()}}
function zones(){return{left:{x:24,y:H-170,w:110,h:110},right:{x:144,y:H-170,w:110,h:110},thrust:{x:W-254,y:H-185,w:110,h:110},fire:{x:W-134,y:H-185,w:110,h:110}}}
function setTouches(ev){keys.left=keys.right=keys.thrust=keys.fire=false;const r=c.getBoundingClientRect(),z=zones();for(const t of ev.touches){let cx=(t.clientX-r.left)*(c.width/r.width),cy=(t.clientY-r.top)*(c.height/r.height);let x=(cx-ox)/scale,y=(cy-oy)/scale;for(const[k,b]of Object.entries(z))if(x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h)keys[k]=true}ev.preventDefault()}
c.addEventListener('touchstart',setTouches,{passive:false});c.addEventListener('touchmove',setTouches,{passive:false});c.addEventListener('touchend',setTouches,{passive:false});
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function draw(){ctx.setTransform(scale,0,0,scale,ox,oy);ctx.fillStyle='#08111f';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';for(const s of stars)ctx.fillRect(s.x,s.y,s.s,s.s);ctx.fillStyle='#25d0ff';ctx.fillRect(0,FLOOR,W,7);ctx.fillStyle='#1f7b42';ctx.fillRect(80,500,240,16);ctx.fillRect(430,605,260,16);ctx.fillRect(780,560,330,16);
ctx.fillStyle='#d9d9d9';ctx.fillRect(1120,470,70,145);ctx.fillStyle='#ff4d22';ctx.beginPath();ctx.moveTo(1120,470);ctx.lineTo(1155,420);ctx.lineTo(1190,470);ctx.fill();ctx.fillStyle='#25d0ff';ctx.fillRect(1140,500,30,35);
for(const p of pickups){if(p.t)continue;ctx.fillStyle=p.k==='part'?'#ffde29':'#ff7a22';rr(p.x-18,p.y-18,36,36,5);ctx.fillStyle='#08111f';ctx.font='bold 12px monospace';ctx.fillText(p.k==='part'?'P':'F',p.x-4,p.y+4)}const cols=['#ff3b30','#ffde29','#00e676','#d66cff'];for(const e of enemies){ctx.fillStyle=cols[e.t];ctx.beginPath();ctx.arc(e.x,e.y,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#08111f';ctx.fillRect(e.x-10,e.y-3,20,6)}ctx.fillStyle='#ffe96a';for(const b of bullets)ctx.fillRect(b.x-8,b.y-2,16,4);
ctx.save();ctx.translate(px,py);if(facing<0)ctx.scale(-1,1);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-14,18,0,Math.PI*2);ctx.fill();ctx.fillRect(-15,2,30,34);ctx.fillStyle='#25d0ff';ctx.fillRect(-7,-19,15,10);if(keys.thrust){ctx.fillStyle='#ff4d22';ctx.beginPath();ctx.moveTo(-10,36);ctx.lineTo(0,58);ctx.lineTo(10,36);ctx.fill()}ctx.restore();
ctx.fillStyle='#fff';ctx.font='bold 26px monospace';ctx.fillText(`SCORE ${String(score).padStart(6,'0')}`,25,38);ctx.fillText(`LIVES ${lives}`,25,72);ctx.fillText(`STAGE ${stage}`,W-190,38);ctx.fillText(`PARTS ${parts}/3  FUEL ${fuel}/1`,W-300,72);const z=zones();ctx.globalAlpha=.28;ctx.fillStyle='#fff';for(const b of Object.values(z))rr(b.x,b.y,b.w,b.h,24);ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.font='bold 44px sans-serif';ctx.fillText('◀',z.left.x+34,z.left.y+68);ctx.fillText('▶',z.right.x+34,z.right.y+68);ctx.font='bold 22px sans-serif';ctx.fillText('JET',z.thrust.x+32,z.thrust.y+64);ctx.fillText('FIRE',z.fire.x+23,z.fire.y+64);if(gameOver){ctx.fillStyle='#000c';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='bold 58px monospace';ctx.fillText('GAME OVER',W/2-180,H/2)}ctx.setTransform(1,0,0,1,0,0)}
function loop(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');let installPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;const b=document.getElementById('install');b.hidden=false;b.onclick=async()=>{await installPrompt.prompt();b.hidden=true}});
